Option Explicit On

Public Class order_list
  
    Dim FormOK As Boolean
    Dim OrderNo As String = " "
    Dim custcode As String = ""
    Dim StrOrderType As String = ""
    Dim strInternalType As String = "Normal" ' Internal Order Fixture, Profile
    Dim status As String = "" ' Order Status
    Dim Da_order As New MySql.Data.MySqlClient.MySqlDataAdapter
    Dim flag As Integer = 0
    Private strType As String 'Profile, Service, Fabrication


    Public Sub New()


        ' This call is required by the Windows Form Designer.
        InitializeComponent()

        StrOrderType = "All"
        setupFormData()
       


    End Sub
    Public Sub New(ByVal listType As String, ByVal Type As String, Optional ByVal InternalType As String = "Normal")

        '***** Type is Service, Profile, Fabrication etc
        ' This call is required by the Windows Form Designer.
        InitializeComponent()

        StrOrderType = listType
        strType = Type
        strInternalType = InternalType
        setupFormData()
        Me.Label_Header.Text += " " & Type & " - " & listType

        ' Add any initialization after the InitializeComponent() call.

    End Sub
    
    Public WriteOnly Property ListType() As String
        Set(ByVal value As String)
            StrOrderType = value
            setDA_OrderList()
        End Set
    End Property
    Private Sub setupFormData()
        setDA_OrderList()
        Bs_Cust.DataSource = Orders.CustList
        BS_Status.DataSource = Orders.OrderStatusList
        setStatusColour()

    End Sub

    Private Sub setDA_OrderList()

        'Dim SQL As String = "SELECT  o.`Purchase_Order`,o.`Order_No`,o.`Order_Date`,  o.`Delivery_Date`, o.`Contact_Name`, o.`Order_Status`, " _
        '           & "o.`Special_Instructions`,o.`Order_type`,o.`Cust_code`,c.Cust_name FROM magodmis.order_list o,magodmis.cust_data c " _
        '           & "WHERE o.Type= @Type AND o.cust_code=c.cust_code AND o.order_status like @order_Status ORDER BY o.`Order_Date` DESC ;"
        'SQL = "SELECT  o.* ,c.Cust_name FROM magodmis.order_list o,magodmis.cust_data c 
        '            WHERE o.Type= @Type AND o.cust_code=c.cust_code 
        '            AND o.order_status like @order_Status ORDER BY o.`Order_Date` DESC ;"
        Da_order = Orders.getDBLink.getMySqlDataAdopter

        Da_order.SelectCommand.Parameters.AddWithValue("@Order_status", "Created")
        Da_order.SelectCommand.Parameters.AddWithValue("@Type", strType)
        'Da_order.SelectCommand.CommandText = SQL
        Dim SqlBuild As New System.Text.StringBuilder

        With SqlBuild
            .Append("SELECT o.*,c.Cust_name FROM magodmis.order_list o,magodmis.cust_data c ")
            .Append("WHERE o.cust_code=c.cust_code AND  o.Type= @Type ")

            Select Case strInternalType

                Case "Fixture"
                    .Append(" AND `Order-Ref` like 'Fixture' ")
                Case "Profile"
                    .Append(" AND `Order-Ref` like 'Profile'  ")
                Case Else
                    .Append(" AND `Order-Ref` is null ")
            End Select
        End With

        Select Case StrOrderType
            Case "Closed"
                SqlBuild.Append(" AND o.order_status like @order_Status")
                '  Da_order.SelectCommand.Parameters("@order_Status").Value = "%" & StrOrderType
            Case "Processing"
                SqlBuild.Append(" AND not( order_status ='created' OR order_status ='Suspended' OR order_status ='Cancelled' OR order_status ='Closed' ")
                SqlBuild.Append(" OR order_status ='Closed' OR order_status ='ShortClosed'OR order_status ='Completed' OR order_status ='Suspended'  OR order_status ='Dispatched'  ) ")

            Case "All"
              
            Case Else

                SqlBuild.Append(" AND o.order_status like @order_Status ")
                Da_order.SelectCommand.Parameters("@order_Status").Value = StrOrderType

        End Select
        SqlBuild.Append("ORDER BY o.`Order_Date` DESC,o.Order_No Desc;")

        StrOrderType = "Complete"
        Orders1.Order_List.Clear()
        Da_order.SelectCommand.CommandText = SqlBuild.ToString
        Da_order.Fill(Orders1.Order_List)
        setStatusColour()
        FormOK = True
    End Sub

    Private Sub set_orderStatusCombo()



    End Sub

    Private Sub DGV_OrderList_CellContentDoubleClick(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs) Handles DGV_OrderList.CellContentDoubleClick
        openorder()
    End Sub

    Private Sub EditableGrid_DataError(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewDataErrorEventArgs) Handles DGV_OrderList.DataError
        ''Don't Delete this Event as it is required if any error generated by datagrid
    End Sub
  
    Private Sub setStatusColour()
        Dim str As String
        For Each Dr As System.Windows.Forms.DataGridViewRow In Me.DGV_OrderList.Rows

            If Not Dr.IsNewRow Then
                str = Dr.Cells("order_status").Value.ToString
                Select Case str
                    Case "Recorded"
                        Dr.DefaultCellStyle.BackColor = Drawing.Color.GreenYellow
                    Case "Processing"
                        Dr.DefaultCellStyle.BackColor = Drawing.Color.Honeydew
                    Case "Completed"
                        Dr.DefaultCellStyle.BackColor = Drawing.Color.LightGreen
                    Case "Ready"
                        Dr.DefaultCellStyle.BackColor = Drawing.Color.YellowGreen
                    Case "Dispatched"
                        Dr.DefaultCellStyle.BackColor = Drawing.Color.Green
                End Select

            End If
        Next
    End Sub

    Private Sub call_setupdata()
        If FormOK Then
            If custcode <> "" And StrOrderType <> "" And status = "" Then
                Bs_order.Filter = "order_Type='" & StrOrderType & "' AND Cust_Code='" & custcode & "'"
            ElseIf custcode = "" And StrOrderType <> "" And status = "" Then
                Bs_order.Filter = "order_Type='" & StrOrderType & "'"
            ElseIf custcode <> "" And StrOrderType = "" And status = "" Then
                Bs_order.Filter = "Cust_Code='" & custcode & "'"
            ElseIf custcode = "" And StrOrderType = "" And status <> "" Then
                Bs_order.Filter = "order_status='" & status & "'"
            ElseIf custcode <> "" And StrOrderType = "" And status <> "" Then
                Bs_order.Filter = "order_status='" & status & "' AND Cust_Code='" & custcode & "'"
            ElseIf custcode = "" And StrOrderType <> "" And status <> "" Then
                Bs_order.Filter = "order_status='" & status & "' AND order_Type='" & StrOrderType & "'"
            ElseIf custcode <> "" And StrOrderType <> "" And status <> "" Then
                Bs_order.Filter = "order_status='" & status & "' AND order_Type='" & StrOrderType & "' AND Cust_Code='" & custcode & "'"
            Else
                Bs_order.RemoveFilter()
            End If
        End If

    End Sub
    Private Sub Button3_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnExit.Click
        Me.Close()
    End Sub


    Private Sub cmb_custname_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmb_custname.SelectedIndexChanged
        If flag = 1 Then
            If Not cmb_custname.SelectedValue Is Nothing Then
                custcode = cmb_custname.SelectedValue.ToString()
                call_setupdata()
            End If

        End If

    End Sub

    Private Sub RadioButton1_Click1(ByVal sender As Object, ByVal e As System.EventArgs) Handles RadioButton1.Click
        StrOrderType = "Complete"
        call_setupdata()
    End Sub

    Private Sub RadioButton2_Click1(ByVal sender As Object, ByVal e As System.EventArgs) Handles RadioButton2.Click
        StrOrderType = "scheduled"
        call_setupdata()
    End Sub

    Private Sub RadioButton3_Click1(ByVal sender As Object, ByVal e As System.EventArgs) Handles RadioButton3.Click
        StrOrderType = "Open"
        call_setupdata()
    End Sub

    Private Sub Button1_Click_1(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        custcode = ""
        StrOrderType = ""
        status = ""
        RadioButton1.Checked = False
        RadioButton2.Checked = False
        RadioButton3.Checked = False
        call_setupdata()
    End Sub

   

    Private Sub Button6_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn_openOrdere.Click
        openorder()
    End Sub

    Private Sub openorder()
        Using X As New Order(DGV_OrderList.CurrentRow.Cells("Order_no").Value.ToString)
            X.ShowDialog()
        End Using

    End Sub

    Private Sub Form_order_list_lt_FormClosing(ByVal sender As Object, ByVal e As System.Windows.Forms.FormClosingEventArgs) Handles Me.FormClosing
    
        Me.Visible = False
    End Sub

    Private Sub Form_order_list_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        flag = 1
    End Sub

    Private Sub cmb_orderstatus_SelectedValueChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles cmb_orderstatus.SelectedValueChanged
        If flag = 1 Then
            If Not cmb_orderstatus.SelectedValue Is Nothing Then
                status = cmb_orderstatus.SelectedValue.ToString()
                call_setupdata()
            End If

        End If
    End Sub

  

   
End Class

